name: Create ALZ Portal Test URLs

on:
  pull_request:
    types:
      - opened
    branches:
      - url-creator-action
    paths:
      - "eslzArm/**"
  workflow_dispatch: {}

env:
  public_url_pt1: "https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F"
  public_url_pt2: "%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F"
  public_url_pt3: "eslzArm%2Feslz-portal.json"
  fairfax_url_pt1: "https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F"
  fairfax_url_pt2: "%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F"
  fairfax_url_pt3: "eslzArm%2Ffairfaxeslz-portal.json"
  url_2f: "%2F"

jobs:
  printJob:
    name: Generate ALZ Accelerator Test URLs
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Information
        id: get-pr-info
        shell: pwsh
        run: |
          $GH_CONTEXT_PS = Get-Content '${{ github.event }}' | ConvertFrom-Json -Depth 10

          $forkRepoFullName = $GH_CONTEXT_PS.pull_request.head.repo.full_name
          $forkOrgName = $forkRepoFullName.Split('/',2)[0]
          $forkRepoName = $forkRepoFullName.Split('/',2)[1]
          $forkBranchName = $GH_CONTEXT_PS.pull_request.head.ref

          $publicTestUrl = ${{ env.public_url_pt1 }} + $forkOrgName + ${{ env.url_2f }} + $forkRepoName + ${{ env.url_2f }} + $forkBranchName + ${{ env.public_url_pt2 }} + $forkOrgName + ${{ env.url_2f }} + $forkRepoName + ${{ env.url_2f }} + $forkBranchName + ${{ env.url_2f }} + ${{ env.public_url_pt3 }}
          $fairfaxTestUrl = ${{ env.fairfax_url_pt1 }} + $forkOrgName + ${{ env.url_2f }} + $forkRepoName + ${{ env.url_2f }} + $forkBranchName + ${{ env.fairfax_url_pt2 }}" + $forkOrgName + ${{ env.url_2f }} + $forkRepoName + ${{ env.url_2f }} + $forkBranchName + ${{ env.url_2f }} + ${{ env.fairfax_url_pt3 }}

          Write-Output ::set-output name=PUBLIC_TEST_URL_OUT::$( $publicTestUrl)
          Write-Output ::set-output name=FAIRFAX_TEST_URL_OUT::$( $fairfaxTestUrl)


      - name: Comment PR With Public Test URL
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "ALZ Accelerator Public Test URL: ${{ steps.get-pr-info.outputs.PUBLIC_TEST_URL_OUT }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR With Fairfax Test URL
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "ALZ Accelerator Fairfax Test URL: ${{ steps.get-pr-info.outputs.FAIRFAX_TEST_URL_OUT }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
